version: "3.8"
services:
  # API Gateways
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
      args:
        - SERVICE_NAME=gateway
    command: pnpm run start:dev gateway
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    networks:
      - engl-rush-network
  # Microservices
  user-query:
    build:
      context: .
      dockerfile: ./apps/user/user-query/Dockerfile
      target: development
      args:
        - DOMAIN_NAME=user
        - SERVICE_NAME=user-query
    command: pnpm run start:dev user-query
    volumes:
      - .:/usr/src/app
    networks:
      - engl-rush-network
networks:
  engl-rush-network:
    external: true
